# Generated by Django 5.2.7 on 2025-12-19 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0002_alter_auditlog_options_alter_experiment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Short code, e.g. NARL, NaCRRI, NaSaRRI', max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('TISSUE', 'Tissue'), ('SERUM', 'Serum'), ('SOIL', 'Soil'), ('WATER', 'Water'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Short lab code, e.g. BIOTECH, TC, SOIL', max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('lab_type', models.CharField(choices=[('BIOTECH', 'Biotechnology'), ('TISSUE_CULTURE', 'Tissue Culture'), ('FBA', 'Food Biosciences'), ('SOIL', 'Soil Science'), ('WATER', 'Water Quality'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratories', to='lims_core.institute')),
            ],
            options={
                'ordering': ['institute__code', 'code'],
                'unique_together': {('institute', 'code')},
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='lims_core.laboratory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='lims_core.laboratory'),
        ),
        migrations.AddField(
            model_name='sample',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='lims_core.laboratory'),
        ),
    ]
