# Generated by Django 5.2.7 on 2025-12-19 19:14

from django.db import migrations


def assign_default_laboratory(apps, schema_editor):
    Institute = apps.get_model("lims_core", "Institute")
    Laboratory = apps.get_model("lims_core", "Laboratory")

    Project = apps.get_model("lims_core", "Project")
    Sample = apps.get_model("lims_core", "Sample")
    Experiment = apps.get_model("lims_core", "Experiment")
    InventoryItem = apps.get_model("lims_core", "InventoryItem")

    # Pick the first institute (legacy data owner)
    institute = Institute.objects.first()
    if not institute:
        return

    # Create or get a default laboratory
    lab, _ = Laboratory.objects.get_or_create(
        institute=institute,
        name="Central Laboratory",
        defaults={
            "location": institute.location or "Unknown",
            "is_active": True,
        },
    )

    # Backfill lab into existing records
    for model in (Project, Sample, Experiment, InventoryItem):
        if hasattr(model, "laboratory"):
            model.objects.filter(laboratory__isnull=True).update(laboratory=lab)


class Migration(migrations.Migration):

    dependencies = [
        ("lims_core", "0003_institute_alter_sample_sample_type_laboratory_and_more"),
    ]

    operations = [
        migrations.RunPython(assign_default_laboratory, migrations.RunPython.noop),
    ]
