# Generated by Django 5.2.7 on 2025-12-20 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0004_backfill_default_laboratory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('INTERN', 'Intern'), ('VOLUNTEER', 'Volunteer'), ('VISITOR', 'Visitor'), ('CONTRACTOR', 'Contractor'), ('STUDENT', 'Student')], max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='experiment',
            name='experiment_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='project',
            name='project_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='sample',
            name='sample_id_not_blank',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_action_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryitem',
            name='inv_cat_exp_idx',
        ),
        migrations.RemoveIndex(
            model_name='sample',
            name='sample_proj_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='protocol_reference',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='results',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='lab_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='collected_on',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='storage_location',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='lims_core.laboratory'),
        ),
        migrations.AddField(
            model_name='project',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='lims_core.laboratory'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_roles', to='lims_core.laboratory'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.CharField(default='PLANNED', max_length=50),
        ),
        migrations.AlterField(
            model_name='institute',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='lims_core.laboratory'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(default='REGISTERED', max_length=50),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'laboratory', 'role')},
        ),
        migrations.AddField(
            model_name='staffmember',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='lims_core.institute'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='lims_core.laboratory'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
