# Generated by Django 5.2.7 on 2025-12-24 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0006_workflowtransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sample', 'Sample'), ('experiment', 'Experiment')], max_length=32)),
                ('object_id', models.PositiveIntegerField()),
                ('from_status', models.CharField(max_length=64)),
                ('to_status', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'object_id'], name='lims_core_w_kind_65c00d_idx')],
            },
        ),
    ]
