# Generated by Django 5.2.7 on 2025-12-24 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0007_workflowevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('object_id', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=32)),
                ('sla_seconds', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-triggered_at',),
                'unique_together': {('kind', 'object_id', 'state')},
            },
        ),
    ]
