# Generated by Django 5.2.7 on 2025-12-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0009_alter_experiment_status_alter_sample_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable sample name', max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.CharField(help_text='Primary laboratory sample identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(blank=True, help_text='e.g. leaf, explant, blood, tissue, soil', max_length=50),
        ),
        migrations.CreateModel(
            name='SampleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_code', models.CharField(help_text='Batch or submission identifier', max_length=100, unique=True)),
                ('collected_at', models.DateTimeField(blank=True, help_text='Date and time samples were collected', null=True)),
                ('collected_by', models.CharField(blank=True, help_text='Person or team who collected the samples', max_length=255)),
                ('client_name', models.CharField(blank=True, help_text='Client or submitting entity', max_length=255)),
                ('collection_site', models.CharField(blank=True, help_text='Collection site or location', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Batch-level notes')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_batches', to='lims_core.laboratory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Collection or submission batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='lims_core.samplebatch'),
        ),
    ]
