# Generated by Django 5.2.7 on 2025-12-27 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0010_sample_name_alter_sample_sample_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplebatch',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sample_batches', to='lims_core.project'),
        ),
        migrations.AlterField(
            model_name='samplebatch',
            name='batch_code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='samplebatch',
            name='client_name',
            field=models.CharField(blank=True, help_text='Client or submitting organization (if external)', max_length=255),
        ),
        migrations.AlterField(
            model_name='samplebatch',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplebatch',
            name='collected_by',
            field=models.CharField(blank=True, help_text='Person or team that collected the samples', max_length=255),
        ),
        migrations.AlterField(
            model_name='samplebatch',
            name='collection_site',
            field=models.CharField(blank=True, help_text='Field site, farm, greenhouse, facility, etc.', max_length=255),
        ),
        migrations.AlterField(
            model_name='samplebatch',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
