# Generated by Django 5.2.7 on 2025-12-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0011_samplebatch_project_alter_samplebatch_batch_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_type', models.CharField(help_text='e.g. soils, water, biotech, fisheries, tissue_culture', max_length=64)),
                ('schema_code', models.CharField(help_text='Logical schema identifier, e.g. SOIL_LAB, WATER_QUALITY', max_length=64)),
                ('schema_version', models.CharField(default='v1', help_text='Schema version applied to this laboratory', max_length=16)),
                ('description', models.TextField(blank=True, help_text='Optional description of lab scope and capabilities')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='lims_core.laboratory')),
            ],
            options={
                'verbose_name': 'Laboratory Profile',
                'verbose_name_plural': 'Laboratory Profiles',
                'ordering': ['laboratory__code'],
            },
        ),
    ]
