# Generated by Django 5.2.7 on 2025-12-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0012_laboratoryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('applies_to', models.CharField(choices=[('sample', 'Sample'), ('batch', 'Batch'), ('experiment', 'Experiment')], max_length=32)),
                ('version', models.CharField(default='v1', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_schemas', to='lims_core.laboratoryprofile')),
            ],
            options={
                'unique_together': {('laboratory_profile', 'code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MetadataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice')], max_length=32)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated values for choice fields')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='lims_core.metadataschema')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
