# Generated by Django 5.2.7 on 2025-12-29 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0013_metadataschema_metadatafield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadatafield',
            unique_together={('schema', 'code')},
        ),
        migrations.CreateModel(
            name='MetadataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('sample', 'Sample'), ('batch', 'Batch'), ('experiment', 'Experiment')], max_length=32)),
                ('object_id', models.PositiveIntegerField()),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schema_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='lims_core.metadatafield')),
            ],
            options={
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='lims_core_m_object__637b0d_idx')],
                'unique_together': {('schema_field', 'object_type', 'object_id')},
            },
        ),
    ]
