# Generated by Django 5.2.7 on 2025-12-30 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0015_bootstrap_metadata_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier, e.g. SOIL_CHEMISTRY, WATER_QUALITY', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable name, e.g. Soil Chemistry', max_length=128)),
                ('description', models.TextField(blank=True, help_text='Optional description of analytical scope')),
                ('category', models.CharField(blank=True, help_text='Optional grouping, e.g. environmental, food, biological', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analysis Context',
                'verbose_name_plural': 'Analysis Contexts',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='laboratoryprofile',
            name='lab_type',
            field=models.CharField(help_text='e.g. soils, water, biotech, food_science, biochemistry', max_length=64),
        ),
        migrations.AlterField(
            model_name='laboratoryprofile',
            name='schema_code',
            field=models.CharField(help_text='Logical default schema identifier, e.g. INTAKE_CORE', max_length=64),
        ),
        migrations.AlterField(
            model_name='laboratoryprofile',
            name='schema_version',
            field=models.CharField(default='v1', help_text='Default schema version applied to this laboratory', max_length=16),
        ),
        migrations.AddField(
            model_name='laboratoryprofile',
            name='default_analysis_context',
            field=models.ForeignKey(blank=True, help_text='Default analysis context for new samples in this lab (e.g. SOIL_CHEMISTRY, WATER_QUALITY, FOOD_SAFETY).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_labs', to='lims_core.analysiscontext'),
        ),
    ]
