# Generated by Django 5.2.7 on 2025-12-30 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0016_analysiscontext_alter_laboratoryprofile_lab_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadatafield',
            options={'ordering': ['schema', 'order'], 'verbose_name': 'Metadata Field', 'verbose_name_plural': 'Metadata Fields'},
        ),
        migrations.AlterModelOptions(
            name='metadataschema',
            options={'ordering': ['code', 'version'], 'verbose_name': 'Metadata Schema', 'verbose_name_plural': 'Metadata Schemas'},
        ),
        migrations.AlterModelOptions(
            name='metadatavalue',
            options={'verbose_name': 'Metadata Value', 'verbose_name_plural': 'Metadata Values'},
        ),
        migrations.AlterUniqueTogether(
            name='metadataschema',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='metadataschema',
            name='analysis_context',
            field=models.ForeignKey(blank=True, help_text='Optional analysis context (e.g. Soil Fertility, Food Safety)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metadata_schemas', to='lims_core.analysiscontext'),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='code',
            field=models.CharField(help_text='Machine-readable field code', max_length=64),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('choice', 'Choice')], default='text', max_length=16),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='help_text',
            field=models.TextField(blank=True, help_text='Optional guidance for users'),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='label',
            field=models.CharField(help_text='Human-readable field label', max_length=128),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the schema'),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='required',
            field=models.BooleanField(default=False, help_text='Whether this field is mandatory'),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='schema',
            field=models.ForeignKey(help_text='Schema this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='lims_core.metadataschema'),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='applies_to',
            field=models.CharField(help_text='Object type this schema applies to (e.g. sample, batch)', max_length=64),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='code',
            field=models.CharField(help_text='Logical schema identifier (e.g. SAMPLE_CORE, WATER_QUALITY)', max_length=64),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of schema purpose'),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this schema is currently active'),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='laboratory_profile',
            field=models.ForeignKey(help_text='Laboratory profile this schema belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='metadata_schemas', to='lims_core.laboratoryprofile'),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='name',
            field=models.CharField(help_text='Human-readable schema name', max_length=128),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='version',
            field=models.CharField(default='v1', help_text='Schema version identifier', max_length=16),
        ),
        migrations.AlterField(
            model_name='metadatavalue',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who last set this value', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='metadatavalue',
            name='object_id',
            field=models.PositiveIntegerField(help_text='Primary key of the target object'),
        ),
        migrations.AlterField(
            model_name='metadatavalue',
            name='object_type',
            field=models.CharField(help_text='Object type (e.g. sample, batch)', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='metadataschema',
            unique_together={('laboratory_profile', 'analysis_context', 'code', 'version', 'applies_to')},
        ),
    ]
