# Generated by Django 5.2.7 on 2025-12-30 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0017_alter_metadatafield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='analysis_context',
            field=models.ForeignKey(blank=True, help_text='Optional analysis context. Leave blank for tissue culture, experiments, method development, or non-analytical samples.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='lims_core.analysiscontext'),
        ),
    ]
