# Generated by Django 5.2.7 on 2025-12-31 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0022_alter_experiment_analysis_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataschema',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether this schema is locked for accreditation'),
        ),
        migrations.AddField(
            model_name='metadataschema',
            name='lock_reason',
            field=models.TextField(blank=True, help_text='Reason for locking (e.g. ISO approval, validation complete)'),
        ),
        migrations.AddField(
            model_name='metadataschema',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when schema was locked', null=True),
        ),
        migrations.AddField(
            model_name='metadataschema',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked this schema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_metadata_schemas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadataschema',
            name='supersedes',
            field=models.ForeignKey(blank=True, help_text='Previous schema version this one supersedes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='lims_core.metadataschema'),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='version',
            field=models.CharField(default='v1', help_text='Schema version identifier (e.g. v1, v2, v3)', max_length=16),
        ),
        migrations.AddIndex(
            model_name='metadataschema',
            index=models.Index(fields=['code'], name='lims_core_m_code_ee5bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='metadataschema',
            index=models.Index(fields=['is_locked'], name='lims_core_m_is_lock_925f31_idx'),
        ),
        migrations.AddIndex(
            model_name='metadataschema',
            index=models.Index(fields=['laboratory_profile', 'applies_to'], name='lims_core_m_laborat_8bc2c7_idx'),
        ),
    ]
