# Generated by Django 5.2.7 on 2025-12-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0023_metadataschema_is_locked_metadataschema_lock_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryprofile',
            name='accreditation_mode',
            field=models.BooleanField(default=False, help_text='If enabled, the laboratory operates in accreditation mode. Only LOCKED metadata schemas may be used at runtime. Edits require schema revision cloning.'),
        ),
        migrations.AddIndex(
            model_name='laboratoryprofile',
            index=models.Index(fields=['accreditation_mode'], name='lims_core_l_accredi_12fff9_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoryprofile',
            index=models.Index(fields=['lab_type'], name='lims_core_l_lab_typ_bdd11a_idx'),
        ),
    ]
