# Generated by Django 5.2.7 on 2026-01-01 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_core', '0024_laboratoryprofile_accreditation_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('schema', 'Schema pack'), ('workflow', 'Workflow pack'), ('role', 'Role pack'), ('ui', 'UI pack')], max_length=20)),
                ('version', models.CharField(default='v1', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_config_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'code'),
            },
        ),
        migrations.CreateModel(
            name='LabPackAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number applies first')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_assignments', to='lims_core.laboratoryprofile')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignments', to='lims_core.configpack')),
            ],
            options={
                'ordering': ('priority', 'pack__code'),
                'unique_together': {('laboratory_profile', 'pack')},
            },
        ),
        migrations.CreateModel(
            name='RolePackDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1', max_length=30)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(limit_choices_to={'kind': 'role'}, on_delete=django.db.models.deletion.CASCADE, related_name='role_defs', to='lims_core.configpack')),
            ],
            options={
                'ordering': ('code', 'version'),
                'unique_together': {('pack', 'code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SchemaPackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=10)),
                ('is_required', models.BooleanField(default=False)),
                ('pack', models.ForeignKey(limit_choices_to={'kind': 'schema'}, on_delete=django.db.models.deletion.CASCADE, related_name='schema_items', to='lims_core.configpack')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_items', to='lims_core.metadataschema')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('pack', 'schema')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowPackDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_kind', models.CharField(choices=[('sample', 'Sample'), ('experiment', 'Experiment')], max_length=30)),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='v1', max_length=30)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_workflow_defs', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(limit_choices_to={'kind': 'workflow'}, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_defs', to='lims_core.configpack')),
            ],
            options={
                'ordering': ('object_kind', 'code', 'version'),
                'unique_together': {('pack', 'object_kind', 'code', 'version')},
            },
        ),
    ]
